name: C++ Unit Tests On PR

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev

    - name: Configure and Build
      run: |
        mkdir -p build && cd build
        cmake ..
        make -j4

    - name: Run tests with ctest
      run: |
        cd build
        ctest --output-on-failure
